# Generated by Django 5.1.7 on 2025-04-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
