# Generated by Django 5.1.7 on 2025-05-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_playlist_playlist_image_alter_album_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_image',
        ),
    ]
