# Generated by Django 5.1.7 on 2025-04-29 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_artist_profile_picture_alter_song_audio_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='realease_date',
            new_name='release_date',
        ),
    ]
