# Generated by Django 5.1.7 on 2025-04-29 04:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_rename_realease_date_song_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
